# Day 9 — Pandas 快速入门
## 核心概念：DataFrame = Python 里的 Excel 表格

In [3]:
import pandas as pd
print("pandas 版本:", pd.__version__)

pandas 版本: 3.0.3

## 2. 手工创建 DataFrame

In [4]:
data = {
    "日期":     ["7-01", "7-02", "7-03", "7-04", "7-05"],
    "股票":     ["茅台", "茅台", "茅台", "茅台", "茅台"],
    "开盘价":   [1800, 1812, 1808, 1820, 1830],
    "收盘价":   [1812, 1808, 1820, 1830, 1825],
    "成交量_万": [520, 480, 610, 550, 490]
}

df = pd.DataFrame(data)
df

     日期  股票   开盘价   收盘价  成交量_万
0  7-01  茅台  1800  1812    520
1  7-02  茅台  1812  1808    480
2  7-03  茅台  1808  1820    610
3  7-04  茅台  1820  1830    550
4  7-05  茅台  1830  1825    490

## 3. 五大核心操作（以后每天都用）

In [ ]:
# ① 看形状（多少行，多少列）
df.shape

In [ ]:
# ② 取某一列
df["收盘价"]

In [5]:
# ③ 统计摘要（平均值、最大最小、标准差...）
df.describe()

               开盘价          收盘价       成交量_万
count     5.000000     5.000000    5.000000
mean   1814.000000  1819.000000  530.000000
std      11.489125     9.055385   52.440442
min    1800.000000  1808.000000  480.000000
25%    1808.000000  1812.000000  490.000000
50%    1812.000000  1820.000000  520.000000
75%    1820.000000  1825.000000  550.000000
max    1830.000000  1830.000000  610.000000

In [6]:
# ④ 筛选符合条件的行
df[df["收盘价"] > 1820]

     日期  股票   开盘价   收盘价  成交量_万
3  7-04  茅台  1820  1830    550
4  7-05  茅台  1830  1825    490

In [7]:
# ⑤ 排序
df.sort_values("成交量_万", ascending=False)

     日期  股票   开盘价   收盘价  成交量_万
2  7-03  茅台  1808  1820    610
3  7-04  茅台  1820  1830    550
0  7-01  茅台  1800  1812    520
4  7-05  茅台  1830  1825    490
1  7-02  茅台  1812  1808    480

## 4. 拉真实数据（akshare / yfinance）
今天网络不通，下次再试：
- akshare: `ak.stock_zh_a_hist(symbol="600519", ...)` 
- yfinance: `yf.Ticker("600519.SS").history(...)`

备注：2026-07-12 两个接口都不可用（代理/限流），不影响今天的学习内容。